# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Super Script
tagline:          'The JS Way'
description:      'A site about JavaScript, with a list of many resources.'
url:              http://super-script.us
baseurl:          '/'
paginate:         5

author:
  name:           'Roger Sperberg'
  url:            https://twitter.com/RogerSPress

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/rsperberg/
